# Generated by Django 5.0.7 on 2024-08-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_user_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forgot_Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('DateTime', models.DateTimeField()),
                ('OTP', models.TextField()),
            ],
        ),
    ]
